### ISSUE TITLE
用的这个版本加 1.5.0-1，客户端版本显示客户端文件配置有误。

### ISSUE THREAD

**Issue by Skyearn** [kuoruan/openwrt-kcptun#2]
硬件是斐讯 k3，系统用的 Lean 的 OpenWrt。路径什么的都配置了，换 client_linux_arm7 也一样。

**Comment by kuoruan** [comment]
你在 ssh 里边执行一下 /usr/bin/kcptun-client -v 看看有输出吗

**Comment by Skyearn** [comment]
Illegal instruction

> 在 2019年4月8日，18:31，Xingwang Liao <notifications@github.com> 写道：
> 
> /usr/bin/kcptun-client -v

**Comment by kuoruan** [comment]
```
cat /usr/lib/os-release
```

**Comment by Skyearn** [comment]
文件我反复确认了几次。

**Comment by kuoruan** [comment]
上面那个命令的输出，贴出来看看

**Comment by Skyearn** [comment]
都在这里。

我也确认了下目录里确实有这个文件。

**Comment by kuoruan** [comment]
内容呢？我先看看你路由器什么架构的

**Comment by Skyearn** [comment]
额，我发的图片，可能没发出去。arm_cortex-a9 的。
root@Al:~# cat /usr/lib/os-release
NAME="OpenWrt"
VERSION="SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
VERSION_ID="snapshot"
HOME_URL="http://openwrt.org/"
BUG_URL="http://bugs.openwrt.org/"
SUPPORT_URL="http://forum.lede-project.org/"
BUILD_ID="r1263-b9a261dc"
LEDE_BOARD="bcm53xx/generic"
LEDE_ARCH="arm_cortex-a9"
LEDE_TAINTS="no-all"
LEDE_DEVICE_MANUFACTURER="OpenWrt"
LEDE_DEVICE_MANUFACTURER_URL="http://openwrt.org/"
LEDE_DEVICE_PRODUCT="Generic"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="OpenWrt SNAPSHOT r1263-b9a261dc"

**Comment by kuoruan** [comment]
https://github.com/kuoruan/openwrt-kcptun/releases/download/v20190401-1/kcptun-client_20190401-1_arm_cortex-a9.ipk

这个文件装进去不行吗？

```
/usr/bin/kcptun-client -v
```
也是 Illegal instruction ？

**Comment by Skyearn** [comment]
稍等，我试试。

**Comment by Skyearn** [comment]
嗯，是的。

**Comment by Skyearn** [comment]
我把之前的删了重装一遍也是一样的 Illegal instruction。

**Comment by kuoruan** [comment]
官方的编译呢？
https://github.com/xtaci/kcptun/releases/download/v20190401/kcptun-linux-arm-20190401.tar.gz

这里边的编译文件都不行吗？

**Comment by Skyearn** [comment]
Permission denied

**Comment by kuoruan** [comment]
先给文件加执行权限，再运行

**Comment by Skyearn** [comment]
加了 chmod 777 client_linux_arm7

**Comment by Skyearn** [comment]
root@Al:~# ls -l client_linux_arm7
-rwxrwxrwx    1 root     root       4239976 Apr  8 18:54 client_linux_arm7
root@Al:~#

**Comment by kuoruan** [comment]
```
./client_linux_arm7 -v
```

**Comment by Skyearn** [comment]
root@Al:~# ./client_linux_arm7 -v
Illegal instruction

> 在 2019年4月8日，19:02，Xingwang Liao <notifications@github.com> 写道：
> 
> ./client_linux_arm7 -v

**Comment by kuoruan** [comment]
压缩包里的所有文件都这样吗？

以前可以吗？哪个版本开始不行的？

**Comment by Skyearn** [comment]
以前我不清楚，我是今天才找到这个项目的。

**Comment by Skyearn** [comment]
我试一下其他的两个文件。

**Comment by Skyearn** [comment]
root@Al:~# ./client_linux_arm5 -v
kcptun version 20190401
root@Al:~# ./client_linux_arm6 -v
Illegal instruction
root@Al:~# 
貌似 arm5 能用……

**Comment by Skyearn** [comment]
我试了下，arm5 的的确可以用……非常感谢您的帮助。

**Comment by kuoruan** [comment]
你先用着官方的版本吧，我找一下原因

**Comment by Skyearn** [comment]
好的，谢谢。

**Comment by kuoruan** [comment]
你测试一下这个文件 https://github.com/kuoruan/openwrt-frp/releases/download/v0.25.3-1/frpc_0.25.3-1_arm_cortex-a9.ipk

在你机器上能跑起来吗？装好之后，运行
```
/usr/bin/frpc -v
```

**Comment by Skyearn** [comment]
不行。
root@Al:/usr/bin# kcptun-client -v
Illegal instruction
root@Al:/usr/bin# frpc -v
Illegal instruction
root@Al:/usr/bin#

**Comment by ghost** [comment]
您好，我看了整个issue，是不是K3 A9的芯片因为golang的原因无法运行kcptun-client呢？

**Comment by kuoruan** [comment]
@MagicKeegan 具体原因未知，但是应该是 OpenWrt 的 Golang 编译过程中，确定 K3 的架构有误。
我这里没有K3，无法确定具体问题，等待有缘人解决。
